### ISSUE TITLE
Dashboard Cassa Gruppo UNO

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour-j#13]

**Comment by AulicinoDiego** [comment]
risolto parzialmente con commit :  407ccf6fef7e3c27c48f6f4139b5fb9ac65ab7e5

**Comment by irenedg** [comment]
risolto parzialmente con commit: a50e0a1fbd4117733af663c3f820700ad0ea54ee

**Comment by AulicinoDiego** [comment]
risolto parzialmente con commit: 97e6dcd94f68312b20125cb2bee8f13aed2b4116

**Comment by RobertaConti-Jarvis** [comment]
risoluzione parziale con commit: 3ec359b6b610bb4b4456266ae0ce60e67785519c

**Comment by RobertaConti-Jarvis** [comment]
risoluzione parziale con commit: ce89c15b1894b09f9dfe238604cf6e6533818c79

**Comment by AulicinoDiego** [comment]
commit: 602f81880155db83d1183f76032bff07f37e517c

**Comment by AulicinoDiego** [comment]
commit : 2ec0aa6a500deb649151f4a9d8ed7a4c59f03d34

**Comment by AulicinoDiego** [comment]
commit: fff73586bdf81c63c6c45db0b2bb847a31fb0469

**Comment by AulicinoDiego** [comment]
commit: 0fa1328d6d829e92947acef8ceb3d5e22f61d5a8
