### ISSUE TITLE
Dashboard Cassa Gruppo DUE

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour-j#14]

**Comment by SamueleM21** [comment]
implementato metodo annullaScontrino lato server e client con commit: 66330a5800275f4c5158d063ab6cacc704a81169

**Comment by lollo996** [comment]
implementato automa e metodi nel  ts con commit adf278c3272ffe5d7b6ee8b4f9028f41e2d50989

**Comment by SamueleM21** [comment]
corretto automa e aggiunto metodo vediPrezzoAction() con commit: 887bfdec2afae9a413aba9c359ba1b57a42bf901

**Comment by SamueleM21** [comment]
create e impl. action in dashboard-automa con commit: 3bd5cfee4666cc97a02e9006a0b5f687ad65c585

**Comment by SamueleM21** [comment]
implementati eventi nei metodi con commit: 20c9a7feed4ba1a0ae45e8998570933f49be3b46

**Comment by Fmarro** [comment]
Implementata interfaccia dashboard cassa 2  con commit: 73eb29b2862ed465a88dfd7bd1caa73074c7ba8b

**Comment by Fmarro** [comment]
chiuso con commit: 018f3be9dfe50b735efe4cf64dd781f999925736
