### ISSUE TITLE
Loop nei #37 e #36. Problema ConfermaEvent

### ISSUE THREAD

**Issue by AlbertoMartinezMontero** [luca-lezzerini/scarsefour-j#38]
Se la classe RicercaState del Automa non viene modificata, al confermare un nuovo prodotto, sconto si entra in un loop infinito.
Abbiamo provato alcune soluzioni. Se  this.automa.gui.aggiungiAction(); (riga 35) viene dichiarato dopo il return di riga 36, quindi in riga 37, funziona bene, anche se viene dichiarato un errore per codice non raggiungibile.
Non essendo nostra la creazione del automa, e generando la soluzione trovata un Unreachable code detected, chiediamo a voi come si può risolvere.

**Comment by AulicinoDiego** [comment]
la modifica dell'automaCrud non è stata fatta dal mio gruppo, quindi chiedi a chi l'ha modificato a limite.

**Comment by AlbertoMartinezMontero** [comment]
Errore di valutazione del problema
