### ISSUE TITLE
Creare CSS comune

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour-j#4]
Stessa struttura di conto bancario.
Si chiama thema.css e si mette nella stessa posizione

**Comment by AndreaTangucci** [comment]
Creato file theme.css con commit 13d33838086d04aba8e61e6d516882f1c64edfe8

**Comment by AndreaTangucci** [comment]
Chiuso con commit d0ddaacd0d689811a07862c2389a3f938aa62122
