### ISSUE TITLE
Problema Generazione Dati Test

### ISSUE THREAD

**Issue by AulicinoDiego** [luca-lezzerini/scarsefour-j#41]

**Comment by AulicinoDiego** [comment]
[log_errore_generazione_dati.txt](https://github.com/luca-lezzerini/scarsefour-j/files/6237907/log_errore_generazione_dati.txt)

**Comment by luca-lezzerini** [comment]
Per generare prodotti non linkati a nulla si duplicavano codici e ean. Risolto cambiando con xean e xcodice il prefisso del codice e dell'ean e agiungendo univocità a codice e ean in prodotto
