### ISSUE TITLE
DashboardTreServiceImpl in annullaScontrino riciclare lo scontrino precedente senza ricrearlo

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour-j#56]
Quando si annulla uno scontrino è sufficiente rimuovere le righe, disassociandole. Lo scontrino che rimane è, a tutti gli effetti, uno scontrino vuoto.
Modificare in tal senso il metodo senza creare un nuovo scontrino

**Comment by AndreaTangucci** [comment]
Chiuso con commit 9056c8b2eeca14f77d4f7292b4bee902561038c5
