### ISSUE TITLE
DashboardTreServiceImpl centralizzare il calcolo del totale

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour-j#58]
Creare un metodo privato calcolaTotale che accetti uno scontrino e ritorni un valore double con il totale dello scontrino.
Utilizzare tale metodo in tutti i punti in cui viene calcolato il totale

**Comment by mainieritm** [comment]
Risolto con commit 9f4203eb79304bbfabccf1720cea4eea3b701bc3
