### ISSUE TITLE
DashboardDueServiceImpl metodo annullaScontrino deve riciclare lo scontrino e non cancella le righe dello scontrino

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour-j#70]
Quando si annulla uno scontrino l'istanza dello stesso deve essere riciclata come nuovo scontrino, senza crearne un altro.
Le righe devono essere cancellate dal DB.
Attenzione a rimuovere le associazioni fantasma lato scontrino con le righe.

**Comment by Fmarro** [comment]
risolto con commit: c31035d5fe225561ca6c2cf33cc4038d6f1c81ee
