### ISSUE TITLE
UC Anagrafica Cassiere

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/scarsefour-j#9]

**Comment by irenedg** [comment]
Risoluzione parziale con commit: 5cbd11143bfe49ba96b728841a958f76b424bd85

**Comment by AulicinoDiego** [comment]
Risoluzione parziale con commit : 321996469359768fd68e2bc9575807f828cd43ce

**Comment by irenedg** [comment]
Risoluzione parziale con commit: 62e726947cea53dfcf715575b0da0602b0284e76

**Comment by g-golia** [comment]
Commit: aabf7c50d6b2c9307b001b2c3d91ef9e4353b15b

**Comment by RobertaConti-Jarvis** [comment]
Commit: 635a947e4db46cb32785c3b4ba6812e0922315e4
